[package]
name = "easyfix"
version = "0.11.0"
authors = ["Łukasz Dańko <lukasz.danko@gmail.com>"]
license = "MIT"
description = "Easy FIX (Financial Information Exchange) engine."
repository = "https://github.com/ldanko/easyfix"
readme = "README.md"
edition = "2021"

[features]
default = []
serialize-messages = ["easyfix-messages/serialize"]
deserialize-messages = ["easyfix-messages/deserialize"]

[dependencies]
easyfix-dictionary = { version = "0.4.0", path = "../easyfix-dictionary" }
easyfix-macros = { version = "0.1.2", path = "../easyfix-macros" }
easyfix-messages = { version = "0.6.0", path = "../easyfix-messages" }
easyfix-session = { version = "0.8.1", path = "../easyfix-session" }
